name: WakaTime Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Her saat başı çalıştırır, isterseniz değiştirebilirsiniz

jobs:
  wakatime-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install wakatime-cli
        run: |
          python -m pip install --upgrade pip
          pip install wakatime-cli

      - name: Run WakaTime sync
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          wakatime --today
