name: Update WakaTime Stats

on:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install wakatime-cli
        run: |
          pip install wakatime

      - name: Configure WakaTime API Key
        run: |
          mkdir -p ~/.wakatime
          echo "[settings]\napi_key = ${{ secrets.WAKATIME_API_KEY }}" > ~/.wakatime.cfg

      - name: Test WakaTime CLI
        run: |
          wakatime-cli --entity . --entity-type file --key ${{ secrets.WAKATIME_API_KEY }} --verbose > waka_output.txt 2>&1 || true
          cat waka_output.txt

      - name: Update WakaTime stats
        run: |
          wakatime-cli --entity . --entity-type file --key ${{ secrets.WAKATIME_API_KEY }} --output json > waka.json || true
          wakatime-cli --entity . --entity-type file --key ${{ secrets.WAKATIME_API_KEY }} --output json > waka_project.json || true
          echo -e "## 📅 WakaTime Weekly Stats:\n\n\`\`\`\n$(cat waka.json)\n\`\`\`\n\n\`\`\`\n$(cat waka_project.json)\n\`\`\`" > waka.md
          sed -i '/<!--START_SECTION:waka-->/r waka.md' README.md

      - name: Commit updated README
        run: |
          git config --global user.name "oguzhansecgel"
          git config --global user.email "oguzhansecgel19@icloud.com"
          git add README.md waka.json waka.md waka_output.txt waka_project.json
          git commit -m "Update WakaTime stats"
          git push
