name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # Bu cron ifadesi her saatte bir çalışır
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install wakatime-cli
        run: |
          pip install wakatime

      - name: Configure WakaTime API Key
        run: |
          mkdir -p ~/.wakatime
          echo "[settings]\napi_key = ${{ secrets.WAKATIME_API_KEY }}" > ~/.wakatime.cfg

      - name: Test WakaTime CLI
        run: |
          wakatime --today --verbose > waka_output.txt 2>&1 || true
          cat waka_output.txt

      - name: Update WakaTime stats
        run: |
          wakatime --today --output json > waka.json || true
          wakatime --project --output json > waka_project.json || true
          echo -e "## 📅 WakaTime Weekly Stats:\n\n\`\`\`\n$(cat waka.json)\n\`\`\`\n\n\`\`\`\n$(cat waka_project.json)\n\`\`\`" > waka.md
          sed -i '/<!--START_SECTION:waka-->/r waka.md' README.md

      - name: Commit updated README
        run: |
          git config --global user.name "your-github-username"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "Update WakaTime stats"
          git push
